version: "3.8"

services:
  app:
    container_name: 'grm-app'
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./src:/go/src/app
    ports:
      - ${GO_API_PORT}:8080
    environment:
      - GO_UID=${HOST_UID}
      - GO_GID=${HOST_GID}
      - GOOSE_DRIVER=mysql
      - GOOSE_DBSTRING=root:${DB_PASS}@tcp(host.docker.internal:${DB_PORT})/${DB_NAME}
    extra_hosts:
      - "host.docker.internal:${DOCKER_BRIDGE_HOST_IP}"
    # restart: always
  db:
    container_name: 'grm-mysql'
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - "${DB_PORT}:${DB_PORT}/tcp"
    command: --port ${DB_PORT}
    extra_hosts:
      - "host.docker.internal:${DOCKER_BRIDGE_HOST_IP}"
volumes:
  db-store:
